import type { ConfigField } from "./types";

/**
 * Client-safe channel metadata. No Node.js dependencies.
 * Used by UI components to render channel lists and config forms.
 */
export interface ChannelMeta {
  type: string;
  displayName: string;
  description: string;
  icon: string;
  setupGuide?: string;
  configFields: ConfigField[];
  hasTest?: boolean;
}

const channelMeta: ChannelMeta[] = [
  {
    type: "telegram",
    displayName: "Telegram",
    description: "Send notifications via Telegram bot",
    icon: "telegram",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create a bot**",
      "Open Telegram, search for **@BotFather**, and send `/newbot`. Follow the prompts to name your bot. Copy the **bot token** it gives you.",
      "",
      "**Step 2: Get your Chat ID**",
      "Decide where you want notifications: your personal chat, or a group.",
      "",
      "**Personal chat:** Open a conversation with your new bot (search for it by username) and send it any message (e.g. \"hello\"). Then open this URL in your browser:",
      "`https://api.telegram.org/bot<YOUR_BOT_TOKEN>/getUpdates`",
      "Replace `<YOUR_BOT_TOKEN>` with the full token from Step 1 (the whole string including the colon, e.g. `123456:ABC-DEF...`). Look for `\"chat\":{\"id\":123456789}` in the response — that number is your Chat ID.",
      "",
      "**Group chat:** Add the bot to a group, send any message in the group, then open the same URL above. The Chat ID for groups is a negative number like `-1001234567890`.",
      "",
      "**Important:** You must send a message to the bot (or in the group) **before** testing. Bots cannot initiate conversations — they can only reply to chats where a user has already sent a message.",
    ].join("\n"),
    configFields: [
      {
        key: "botToken",
        label: "Bot Token",
        type: "password",
        required: true,
        helpText: "From @BotFather — looks like 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11",
        placeholder: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11",
      },
      {
        key: "chatId",
        label: "Chat ID",
        type: "text",
        required: true,
        helpText:
          "Your personal or group chat ID (a number). See setup guide above for how to find it.",
        placeholder: "123456789",
      },
    ],
  },
  {
    type: "discord",
    displayName: "Discord",
    description: "Send notifications to a Discord channel via webhook",
    icon: "discord",
    hasTest: true,
    setupGuide: [
      "1. Open your Discord server settings",
      "2. Go to **Integrations** > **Webhooks**",
      "3. Click **New Webhook** and select the target channel",
      "4. Copy the webhook URL",
    ].join("\n"),
    configFields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "text",
        required: true,
        helpText: "Found in Server Settings > Integrations > Webhooks",
        placeholder: "https://discord.com/api/webhooks/...",
      },
    ],
  },
  {
    type: "webhook",
    displayName: "Webhook",
    description: "Send notifications to any HTTP endpoint",
    icon: "webhook",
    hasTest: true,
    configFields: [
      {
        key: "url",
        label: "Endpoint URL",
        type: "text",
        required: true,
        helpText:
          "The URL that will receive POST/PUT requests with the notification payload",
        placeholder: "https://api.example.com/notifications",
      },
      {
        key: "method",
        label: "HTTP Method",
        type: "select",
        required: true,
        options: [
          { label: "POST", value: "POST" },
          { label: "PUT", value: "PUT" },
        ],
      },
      {
        key: "headers",
        label: "Custom Headers",
        type: "keyvalue",
        helpText:
          "Additional HTTP headers to send with the request (e.g. Authorization)",
      },
    ],
  },
  {
    type: "slack",
    displayName: "Slack",
    description: "Send notifications to a Slack channel via webhook",
    icon: "slack",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create a Slack App**",
      "Go to [api.slack.com/apps](https://api.slack.com/apps) and click **Create New App** > **From scratch**. Choose a name and workspace.",
      "",
      "**Step 2: Enable Incoming Webhooks**",
      "In your app settings, go to **Incoming Webhooks** and toggle it on.",
      "",
      "**Step 3: Create a Webhook URL**",
      "Click **Add New Webhook to Workspace**, select the channel you want notifications in, and click **Allow**. Copy the webhook URL.",
    ].join("\n"),
    configFields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "text",
        required: true,
        helpText: "From your Slack app's Incoming Webhooks settings",
        placeholder: "https://hooks.slack.com/services/...",
      },
    ],
  },
  {
    type: "teams",
    displayName: "Microsoft Teams",
    description: "Send notifications to a Teams channel via webhook",
    icon: "microsoft-teams",
    hasTest: true,
    setupGuide: [
      "**Step 1: Open the channel or chat**",
      "In Microsoft Teams, open the channel or chat where you want notifications.",
      "",
      "**Step 2: Create a workflow**",
      'Click the **+** button or go to **Workflows**, then select **"Send webhook alerts to a channel"** (for channels) or **"Send webhook alerts to a chat"** (for chats).',
      "",
      "**Step 3: Copy the webhook URL**",
      "Follow the prompts to finish the workflow, then copy the generated webhook URL.",
    ].join("\n"),
    configFields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "text",
        required: true,
        helpText: "From your Teams channel or chat workflow webhook",
        placeholder:
          "https://default<randomid>.environment.api.powerplatform.com:443/...",
      },
    ],
  },
  {
    type: "google-chat",
    displayName: "Google Chat",
    description: "Send notifications to a Google Chat space via webhook",
    icon: "google-chat",
    hasTest: true,
    setupGuide: [
      "**Step 1: Open the space**",
      "In Google Chat, open the space where you want notifications.",
      "",
      "**Step 2: Create a webhook**",
      "Click the space name at the top > **Apps & integrations** > **Webhooks** > **Create**.",
      "",
      "**Step 3: Copy the URL**",
      "Give the webhook a name, optionally set an avatar, and copy the webhook URL.",
    ].join("\n"),
    configFields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "text",
        required: true,
        helpText: "From your Google Chat space's webhook settings",
        placeholder:
          "https://chat.googleapis.com/v1/spaces/.../messages?key=...",
      },
    ],
  },
  {
    type: "matrix",
    displayName: "Matrix",
    description: "Send notifications to a Matrix room (Element, etc.)",
    icon: "matrix",
    hasTest: true,
    setupGuide: [
      "**Highly recommended: create a dedicated user**",
      "The access token grants full access to the account that issued it — including reading all messages and joining or leaving rooms. Create a separate Matrix user for Alphorn and invite it to the room, rather than using your personal account's token.",
      "",
      "**Step 1: Get your access token**",
      "Sign in as the dedicated user in Element, then go to **Settings** > **Help & About** > scroll to **Access Token** and copy it.",
      "",
      "**Step 2: Get the Room ID**",
      "In Element: open the room > **Room Settings** > **Advanced** > copy the **Internal Room ID** (starts with `!`).",
      "",
      "**Step 3: Homeserver URL**",
      "This is your Matrix server URL, e.g. `https://matrix.org` for the default server. If self-hosting, use your server's URL.",
    ].join("\n"),
    configFields: [
      {
        key: "homeserverUrl",
        label: "Homeserver URL",
        type: "text",
        required: true,
        helpText:
          "Your Matrix homeserver URL (e.g. https://matrix.org)",
        placeholder: "https://matrix.org",
      },
      {
        key: "accessToken",
        label: "Access Token",
        type: "password",
        required: true,
        helpText: "From Element: Settings > Help & About > Access Token",
      },
      {
        key: "roomId",
        label: "Room ID",
        type: "text",
        required: true,
        helpText:
          "From Element: Room Settings > Advanced > Internal Room ID",
        placeholder: "!abc123:matrix.org",
      },
    ],
  },
  {
    type: "mattermost",
    displayName: "Mattermost",
    description: "Send notifications to a Mattermost channel via webhook",
    icon: "mattermost",
    hasTest: true,
    setupGuide: [
      "**Step 1: Enable incoming webhooks**",
      "In Mattermost, go to **System Console** > **Integrations** > **Integration Management** and enable incoming webhooks.",
      "",
      "**Step 2: Create a webhook**",
      "Go to **Integrations** > **Incoming Webhooks** > **Add Incoming Webhook**. Select the channel and save.",
      "",
      "**Step 3: Copy the URL**",
      "Copy the webhook URL provided after creation.",
    ].join("\n"),
    configFields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "text",
        required: true,
        helpText: "From Mattermost: Integrations > Incoming Webhooks",
        placeholder: "https://mattermost.example.com/hooks/...",
      },
    ],
  },
  {
    type: "ntfy",
    displayName: "Ntfy",
    description: "Send push notifications via ntfy (self-hostable)",
    icon: "ntfy",
    hasTest: true,
    setupGuide: [
      "**Step 1: Choose a server**",
      "Use the public server at `https://ntfy.sh` or [self-host your own](https://docs.ntfy.sh/install/).",
      "",
      "**Step 2: Pick a topic**",
      "Choose a unique topic name (e.g. `my-server-alerts`). Anyone who knows the topic name can subscribe, so make it hard to guess.",
      "",
      "**Step 3: Subscribe**",
      "Install the ntfy app on your phone or use the web UI at `https://ntfy.sh/my-topic` to subscribe.",
      "",
      "**Optional: Access token**",
      "If your server requires authentication, create an access token in your ntfy server settings.",
    ].join("\n"),
    configFields: [
      {
        key: "serverUrl",
        label: "Server URL",
        type: "text",
        required: true,
        helpText:
          "Use https://ntfy.sh for the public server or your self-hosted instance URL",
        placeholder: "https://ntfy.sh",
      },
      {
        key: "topic",
        label: "Topic",
        type: "text",
        required: true,
        helpText:
          "The topic name to publish to (e.g. my-notifications)",
        placeholder: "my-notifications",
      },
      {
        key: "accessToken",
        label: "Access Token",
        type: "password",
        helpText: "Optional. Required for private/protected topics",
      },
    ],
  },
  {
    type: "pushover",
    displayName: "Pushover",
    description: "Send push notifications via Pushover",
    icon: "pushover",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create an account**",
      "Sign up at [pushover.net](https://pushover.net). Your **User Key** is shown on the dashboard.",
      "",
      "**Step 2: Create an application**",
      "Go to [pushover.net/apps/build](https://pushover.net/apps/build) and create an application. Copy the **API Token**.",
      "",
      "**Step 3: Install the app**",
      "Install the Pushover app on your phone or desktop to receive notifications.",
    ].join("\n"),
    configFields: [
      {
        key: "apiToken",
        label: "API Token",
        type: "password",
        required: true,
        helpText: "From your Pushover application settings",
      },
      {
        key: "userKey",
        label: "User Key",
        type: "password",
        required: true,
        helpText: "Your Pushover user key, found on your dashboard",
      },
    ],
  },
  {
    type: "gotify",
    displayName: "Gotify",
    description: "Send push notifications via Gotify (self-hostable)",
    icon: "gotify",
    hasTest: true,
    setupGuide: [
      "**Step 1: Set up Gotify**",
      "[Self-host Gotify](https://gotify.net/docs/install) or use an existing instance.",
      "",
      "**Step 2: Create an application**",
      "In the Gotify web UI, go to **Apps** > **Create Application**. Copy the **App Token**.",
      "",
      "**Step 3: Subscribe**",
      "Install the Gotify app on your phone or use the web UI to see notifications.",
    ].join("\n"),
    configFields: [
      {
        key: "serverUrl",
        label: "Server URL",
        type: "text",
        required: true,
        helpText: "Your Gotify server URL",
        placeholder: "https://gotify.example.com",
      },
      {
        key: "appToken",
        label: "App Token",
        type: "password",
        required: true,
        helpText: "From Gotify: Apps > Create Application > copy token",
      },
    ],
  },
  {
    type: "twilio-sms",
    displayName: "Twilio SMS",
    description: "Send notifications via SMS using Twilio",
    icon: "twilio",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create a Twilio account**",
      "Sign up at [twilio.com](https://www.twilio.com). Find your **Account SID** and **Auth Token** on the console dashboard.",
      "",
      "**Step 2: Get a phone number**",
      "Buy or verify a phone number in the Twilio console. This will be your **From** number.",
      "",
      "**Step 3: Add recipient**",
      "Enter the recipient phone number in E.164 format (e.g. `+15551234567`). For trial accounts, verify the number first.",
    ].join("\n"),
    configFields: [
      {
        key: "accountSid",
        label: "Account SID",
        type: "text",
        required: true,
        helpText: "From your Twilio console dashboard",
        placeholder: "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      },
      {
        key: "authToken",
        label: "Auth Token",
        type: "password",
        required: true,
        helpText: "From your Twilio console dashboard",
      },
      {
        key: "from",
        label: "From Number",
        type: "text",
        required: true,
        helpText: "Your Twilio phone number in E.164 format",
        placeholder: "+15551234567",
      },
      {
        key: "to",
        label: "To Number",
        type: "text",
        required: true,
        helpText: "Recipient phone number in E.164 format",
        placeholder: "+15559876543",
      },
    ],
  },
  {
    type: "smtp",
    displayName: "Email (SMTP)",
    description: "Send notifications via email",
    icon: "email",
    hasTest: true,
    setupGuide: [
      "Configure your SMTP server credentials. Common providers:",
      "- **Gmail**: smtp.gmail.com, port 587. Use an [App Password](https://myaccount.google.com/apppasswords)",
      "- **Outlook**: smtp.office365.com, port 587",
      "- **Custom**: Use your mail server's SMTP settings",
    ].join("\n"),
    configFields: [
      {
        key: "host",
        label: "SMTP Host",
        type: "text",
        required: true,
        placeholder: "smtp.gmail.com",
      },
      {
        key: "port",
        label: "Port",
        type: "number",
        required: true,
        helpText: "587 for STARTTLS (recommended), 465 for implicit SSL/TLS",
        placeholder: "587",
      },
      {
        key: "secure",
        label: "Encryption",
        type: "select",
        helpText:
          "Leave on Auto unless your server uses a non-standard port",
        options: [
          { label: "Auto (based on port)", value: "auto" },
          { label: "STARTTLS", value: "starttls" },
          { label: "SSL / Implicit TLS", value: "ssl" },
        ],
      },
      {
        key: "username",
        label: "Username",
        type: "text",
        required: true,
        placeholder: "you@gmail.com",
      },
      {
        key: "password",
        label: "Password",
        type: "password",
        required: true,
        helpText:
          "For Gmail, use an App Password instead of your account password",
      },
      {
        key: "from",
        label: "From Address",
        type: "text",
        required: true,
        placeholder: "notifications@example.com",
      },
      {
        key: "to",
        label: "To Address",
        type: "text",
        required: true,
        helpText:
          "Recipient email address. Separate multiple addresses with commas",
        placeholder: "you@example.com",
      },
    ],
  },
  {
    type: "sse",
    displayName: "Live Stream (SSE)",
    description: "Stream notifications in real-time via Server-Sent Events",
    icon: "sse",
    hasTest: false,
    setupGuide: [
      "**How it works**",
      "This channel streams notifications in real-time using Server-Sent Events (SSE). Any client that supports SSE can connect — browsers, `curl`, scripts, etc.",
      "",
      "**After creating this channel:**",
      "1. Link it to a webhook (just like any other channel)",
      "2. Copy the **Stream URL** shown on the channel edit page",
      "3. Connect with `EventSource` in a browser or `curl -N <url>`",
      "",
      "**Configuration**",
      "Choose **JSON** for structured data or **Plain Text** for a human-readable line. The toggle fields below apply to both formats.",
    ].join("\n"),
    configFields: [
      {
        key: "format",
        label: "Output Format",
        type: "select",
        required: true,
        helpText: "JSON sends structured data, Text sends a human-readable line",
        options: [
          { label: "JSON", value: "json" },
          { label: "Plain Text", value: "text" },
        ],
      },
      {
        key: "includePriority",
        label: "Include Priority",
        type: "switch",
        helpText: "Include the priority field in streamed events",
      },
      {
        key: "includeTags",
        label: "Include Tags",
        type: "switch",
        helpText: "Include the tags field in streamed events",
      },
      {
        key: "includePayload",
        label: "Include Payload",
        type: "switch",
        helpText: "Include the full payload in streamed events",
      },
    ],
  },
  {
    type: "rocketchat",
    displayName: "Rocket.Chat",
    description: "Send notifications to a Rocket.Chat channel via webhook",
    icon: "rocketchat",
    hasTest: true,
    setupGuide: [
      "**Step 1: Enable incoming webhooks**",
      "In Rocket.Chat, go to **Administration** > **Workspace** > **Integrations** and enable incoming webhooks.",
      "",
      "**Step 2: Create a webhook**",
      "Click **New Integration** > **Incoming Webhook**. Select the channel and configure a name.",
      "",
      "**Step 3: Copy the URL**",
      "Save the integration and copy the **Webhook URL** provided.",
    ].join("\n"),
    configFields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "text",
        required: true,
        helpText: "From Administration > Integrations > Incoming Webhook",
        placeholder: "https://rocketchat.example.com/hooks/...",
      },
    ],
  },
  {
    type: "zulip",
    displayName: "Zulip",
    description: "Send notifications to a Zulip stream",
    icon: "zulip",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create a bot**",
      "In Zulip, click on your **User Profile**, go to **Settings** > **Bots** > **Add a new bot**. Choose **Incoming webhook** type.",
      "",
      "**Step 2: Copy credentials**",
      "Copy the bot's **email address** and **API key**.",
      "",
      "**Step 3: Choose a stream and topic**",
      "Pick the stream (channel) and topic where notifications should be posted.",
    ].join("\n"),
    configFields: [
      {
        key: "serverUrl",
        label: "Server URL",
        type: "text",
        required: true,
        helpText: "Your Zulip server URL",
        placeholder: "https://yourorg.zulipchat.com",
      },
      {
        key: "botEmail",
        label: "Bot Email",
        type: "text",
        required: true,
        helpText: "The bot's email address from Settings > Your Bots",
        placeholder: "my-bot@yourorg.zulipchat.com",
      },
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        required: true,
        helpText: "The bot's API key from Settings > Your Bots",
      },
      {
        key: "stream",
        label: "Stream",
        type: "text",
        required: true,
        helpText: "The stream (channel) to post to",
        placeholder: "general",
      },
      {
        key: "topic",
        label: "Topic",
        type: "text",
        required: true,
        helpText: "The topic within the stream",
        placeholder: "notifications",
      },
    ],
  },
  {
    type: "pagerduty",
    displayName: "PagerDuty",
    description: "Create incidents in PagerDuty via Events API v2",
    icon: "pagerduty",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create or select a service**",
      "In PagerDuty, go to **Services** > **Service Directory** and select or create a service.",
      "",
      "**Step 2: Add an integration**",
      "In the service, go to **Integrations** > **Add Integration** > select **Events API v2**.",
      "",
      "**Step 3: Copy the routing key**",
      "Copy the **Integration Key** (routing key) shown after saving.",
    ].join("\n"),
    configFields: [
      {
        key: "routingKey",
        label: "Routing Key",
        type: "password",
        required: true,
        helpText:
          "Integration key from Services > Service > Integrations > Events API v2",
        placeholder: "e93facc04764012d7bfb002500d5d1a6",
      },
      {
        key: "severity",
        label: "Default Severity",
        type: "select",
        required: true,
        helpText: "Severity level for created incidents",
        options: [
          { label: "Critical", value: "critical" },
          { label: "Error", value: "error" },
          { label: "Warning", value: "warning" },
          { label: "Info", value: "info" },
        ],
      },
    ],
  },
  {
    type: "opsgenie",
    displayName: "Opsgenie",
    description: "Create alerts in Opsgenie",
    icon: "opsgenie",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create an API integration**",
      "In Opsgenie, go to **Settings** > **Integration List** > **API** > **Add**.",
      "",
      "**Step 2: Copy the API key**",
      "Copy the **API Key** from the integration settings. Use a 'Create and Close' API integration for full functionality.",
      "",
      "**Step 3: Choose your region**",
      "Select US or EU based on your Opsgenie instance URL (app.opsgenie.com = US, app.eu.opsgenie.com = EU).",
    ].join("\n"),
    configFields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        required: true,
        helpText: "From Settings > Integration List > API > Add",
      },
      {
        key: "region",
        label: "Region",
        type: "select",
        required: true,
        helpText: "Your Opsgenie instance region",
        options: [
          { label: "US (api.opsgenie.com)", value: "us" },
          { label: "EU (api.eu.opsgenie.com)", value: "eu" },
        ],
      },
      {
        key: "priority",
        label: "Default Priority",
        type: "select",
        required: true,
        helpText: "Default priority for created alerts",
        options: [
          { label: "P1 - Critical", value: "P1" },
          { label: "P2 - High", value: "P2" },
          { label: "P3 - Moderate", value: "P3" },
          { label: "P4 - Low", value: "P4" },
          { label: "P5 - Informational", value: "P5" },
        ],
      },
    ],
  },
  {
    type: "sendgrid",
    displayName: "SendGrid",
    description: "Send email notifications via SendGrid",
    icon: "sendgrid",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create an API key**",
      "In SendGrid, go to **Settings** > **API Keys** > **Create API Key**. Give it **Mail Send** permission.",
      "",
      "**Step 2: Verify a sender**",
      "Go to **Settings** > **Sender Authentication** and verify the email address or domain you'll send from.",
      "",
      "**Step 3: Configure**",
      "Enter your API key, verified sender address, and recipient email below.",
    ].join("\n"),
    configFields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        required: true,
        helpText: "From Settings > API Keys (needs Mail Send permission)",
      },
      {
        key: "from",
        label: "From Email",
        type: "text",
        required: true,
        helpText: "Must be a verified sender in SendGrid",
        placeholder: "notifications@example.com",
      },
      {
        key: "fromName",
        label: "From Name",
        type: "text",
        helpText: "Display name for the sender (optional)",
        placeholder: "Alphorn Notifications",
      },
      {
        key: "to",
        label: "To Email",
        type: "text",
        required: true,
        helpText: "Recipient email. Separate multiple with commas",
        placeholder: "you@example.com",
      },
    ],
  },
  {
    type: "mailgun",
    displayName: "Mailgun",
    description: "Send email notifications via Mailgun",
    icon: "mailgun",
    hasTest: true,
    setupGuide: [
      "**Step 1: Get your API key**",
      "In Mailgun, go to your dashboard and find your **Private API Key** under API Keys.",
      "",
      "**Step 2: Set up a domain**",
      "Go to **Sending** > **Domains** and add/verify a sending domain (e.g. `mg.example.com`).",
      "",
      "**Step 3: Configure**",
      "Enter your API key, sending domain, and email addresses below. Choose US or EU based on your Mailgun region.",
    ].join("\n"),
    configFields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        required: true,
        helpText: "Your private API key from the Mailgun dashboard",
      },
      {
        key: "domain",
        label: "Domain",
        type: "text",
        required: true,
        helpText: "Your verified Mailgun sending domain",
        placeholder: "mg.example.com",
      },
      {
        key: "region",
        label: "Region",
        type: "select",
        required: true,
        helpText: "Your Mailgun region",
        options: [
          { label: "US (api.mailgun.net)", value: "us" },
          { label: "EU (api.eu.mailgun.net)", value: "eu" },
        ],
      },
      {
        key: "from",
        label: "From Address",
        type: "text",
        required: true,
        helpText: "Sender address (must match your verified domain)",
        placeholder: "Alphorn <notifications@mg.example.com>",
      },
      {
        key: "to",
        label: "To Address",
        type: "text",
        required: true,
        helpText: "Recipient email. Separate multiple with commas",
        placeholder: "you@example.com",
      },
    ],
  },
  {
    type: "vonage-sms",
    displayName: "Vonage SMS",
    description: "Send SMS notifications via Vonage (Nexmo)",
    icon: "vonage",
    hasTest: true,
    setupGuide: [
      "**Step 1: Create a Vonage account**",
      "Sign up at [vonage.com](https://www.vonage.com) and find your **API Key** and **API Secret** on the dashboard.",
      "",
      "**Step 2: Get a virtual number**",
      "Buy a virtual number in the Vonage dashboard, or use an alphanumeric sender ID (where supported).",
      "",
      "**Step 3: Configure**",
      "Enter your API credentials, sender number/ID, and recipient number below.",
    ].join("\n"),
    configFields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "text",
        required: true,
        helpText: "From your Vonage API dashboard",
        placeholder: "a1b2c3d4",
      },
      {
        key: "apiSecret",
        label: "API Secret",
        type: "password",
        required: true,
        helpText: "From your Vonage API dashboard",
      },
      {
        key: "from",
        label: "From",
        type: "text",
        required: true,
        helpText:
          "Your Vonage virtual number (E.164 format) or alphanumeric sender ID",
        placeholder: "+15551234567",
      },
      {
        key: "to",
        label: "To Number",
        type: "text",
        required: true,
        helpText: "Recipient phone number in E.164 format",
        placeholder: "+15559876543",
      },
    ],
  },
];

export function getAllChannelMeta(): ChannelMeta[] {
  return channelMeta;
}

export function getChannelMeta(type: string): ChannelMeta | undefined {
  return channelMeta.find((m) => m.type === type);
}
